### ISSUE TITLE
Problems with domains

### ISSUE THREAD

**Issue by mkg20001** [mkg20001/libp2p-nodetrust#23]
https://sentry.zion.host/libp2p/nodetrust-server/issues/128/

```
Error: authorizations were not fetched
  File "/home/maciej/libp2p-nodetrust/server/node_modules/acme-v2/node.js", line 573, in null.<anonymous>
    return Promise.reject(new Error('authorizations were not fetched'))
  ?, in null.<anonymous>
  File "internal/process/next_tick.js", line 228, in process._tickDomainCallback

Error: authorizations were not fetched
```

Logs:
```
2018-07-05T14:09:40.845Z libp2p:secio 3. finish - finish
2018-07-05T14:09:40.994Z nodetrust:dns [208.69.32.73:47432#52502]	id0elg2wqm91z50kp2a8ratswm-bk1i9guixoqkpp.ip.libp2p-nodetrust.tk	=>	×
2018-07-05T14:09:41.015Z nodetrust:dns [45.76.11.166:43656#49084]	id0elg2wqm91z50kp2a8ratswm-bk1i9guixoqkpp.ip.libp2p-nodetrust.tk	=>	×
2018-07-05T14:09:41.020Z libp2p:switch:dial dialing QmTiZztTh33nuMFq5ZyW8mCrnzDbPP9zvaGV5UPXrcKR1B
2018-07-05T14:09:41.020Z libp2p:floodsub dialing QmTiZztTh33nuMFq5ZyW8mCrnzDbPP9zvaGV5UPXrcKR1B
2018-07-05T14:09:41.022Z nodetrust:dns [74.125.44.83:61157#29253]	id0elg2wqm91z50kp2a8ratswm-bk1i9guixoqkpp.ip.libp2p-nodetrust.tk	=>	×
2018-07-05T14:09:41.022Z libp2p:switch:dial dialing QmTiZztTh33nuMFq5ZyW8mCrnzDbPP9zvaGV5UPXrcKR1B
2018-07-05T14:09:41.036Z nodetrust:dns [8.0.38.143:27508#6022]	id0elg2wqm91z50kp2a8ratswm-bk1i9guixoqkpp.ip.libp2p-nodetrust.tk	=>	×
2018-07-05T14:09:41.052Z nodetrust:protocol cert for QmTiZztTh33nuMFq5ZyW8mCrnzDbPP9zvaGV5UPXrcKR1B ip488-99-218-136.ip.libp2p-nodetrust.tk
2018-07-05T14:09:41.053Z nodetrust:letsencrypt:acme get certificate QmTiZztTh33nuMFq5ZyW8mCrnzDbPP9zvaGV5UPXrcKR1B id0elhowuyg5nr5yrodcm58r9dn7p5qrujz-lspg-.ip.libp2p-nodetrust.tk, ip488-99-218-136.ip.libp2p-nodetrust.tk
2018-07-05T14:09:42.138Z nodetrust:letsencrypt:acme:queue execute task @QmTiZztTh33nuMFq5ZyW8mCrnzDbPP9zvaGV5UPXrcKR1B,id0elhowuyg5nr5yrodcm58r9dn7p5qrujz-lspg-.ip.libp2p-nodetrust.tk!ip488-99-218-136.ip.libp2p-nodetrust.tk@id0elhowuyg5nr5yrodcm58r9dn7p5qrujz-lspg-.ip.libp2p-nodetrust.tk!ip488-99-218-136.ip.libp2p-nodetrust.tk
2018-07-05T14:09:42.138Z nodetrust:letsencrypt:acme:queue lock domain id0elhowuyg5nr5yrodcm58r9dn7p5qrujz-lspg-.ip.libp2p-nodetrust.tk for @QmTiZztTh33nuMFq5ZyW8mCrnzDbPP9zvaGV5UPXrcKR1B,id0elhowuyg5nr5yrodcm58r9dn7p5qrujz-lspg-.ip.libp2p-nodetrust.tk!ip488-99-218-136.ip.libp2p-nodetrust.tk@id0elhowuyg5nr5yrodcm58r9dn7p5qrujz-lspg-.ip.libp2p-nodetrust.tk!ip488-99-218-136.ip.libp2p-nodetrust.tk
2018-07-05T14:09:42.139Z nodetrust:letsencrypt:acme:queue lock domain ip488-99-218-136.ip.libp2p-nodetrust.tk for @QmTiZztTh33nuMFq5ZyW8mCrnzDbPP9zvaGV5UPXrcKR1B,id0elhowuyg5nr5yrodcm58r9dn7p5qrujz-lspg-.ip.libp2p-nodetrust.tk!ip488-99-218-136.ip.libp2p-nodetrust.tk@id0elhowuyg5nr5yrodcm58r9dn7p5qrujz-lspg-.ip.libp2p-nodetrust.tk!ip488-99-218-136.ip.libp2p-nodetrust.tk
2018-07-05T14:09:42.139Z nodetrust:letsencrypt:acme obtain certificate id0elhowuyg5nr5yrodcm58r9dn7p5qrujz-lspg-.ip.libp2p-nodetrust.tk, ip488-99-218-136.ip.libp2p-nodetrust.tk
2018-07-05T14:09:42.139Z acme-v2 DEBUG get cert 1
2018-07-05T14:09:42.139Z acme-v2 certificates.create
2018-07-05T14:09:42.170Z acme-v2 newOrder
2018-07-05T14:09:42.171Z nodetrust:dns [74.125.44.65:55063#230]	id0elg2wqm91z50kp2a8ratswm-bk1i9guixoqkpp.ip.libp2p-nodetrust.tk	=>	×
2018-07-05T14:09:42.171Z nodetrust:dns [199.7.60.213:35688#46727]	id0elg2wqm91z50kp2a8ratswm-bk1i9guixoqkpp.ip.libp2p-nodetrust.tk	=>	×
2018-07-05T14:09:42.172Z nodetrust:dns [208.69.32.73:32977#58008]	id0elg2wqm91z50kp2a8ratswm-bk1i9guixoqkpp.ip.libp2p-nodetrust.tk	=>	×
2018-07-05T14:09:42.172Z nodetrust:dns [208.69.32.77:53818#15516]	ip4136-243-32-225.ip.libp2p-nodetrust.tk	=>	[A]	136.243.32.225
2018-07-05T14:09:42.173Z nodetrust:dns [199.7.60.213:25873#64241]	id0elg2wqm91z50kp2a8ratswm-bk1i9guixoqkpp.ip.libp2p-nodetrust.tk	=>	×
2018-07-05T14:09:42.173Z nodetrust:dns [192.221.167.13:12864#32555]	ip4136-243-32-225.ip.libp2p-nodetrust.tk	=>	[A]	136.243.32.225
2018-07-05T14:09:42.173Z nodetrust:dns [208.69.32.73:5329#34619]	id0elg2wqm91z50kp2a8ratswm-bk1i9guixoqkpp.ip.libp2p-nodetrust.tk	=>	×
2018-07-05T14:09:42.173Z nodetrust:dns [208.69.32.77:38833#48286]	ip4136-243-32-225.ip.libp2p-nodetrust.tk	=>	[A]	136.243.32.225
2018-07-05T14:09:42.174Z nodetrust:dns [192.221.167.6:33124#37700]	ip4136-243-32-225.ip.libp2p-nodetrust.tk	=>	[A]	136.243.32.225
2018-07-05T14:09:42.174Z nodetrust:dns [74.125.44.84:48953#527]	id0elg2wqm91z50kp2a8ratswm-bk1i9guixoqkpp.ip.libp2p-nodetrust.tk	=>	×
2018-07-05T14:09:42.174Z nodetrust:dns [199.7.60.213:4982#63189]	id0elg2wqm91z50kp2a8ratswm-bk1i9guixoqkpp.ip.libp2p-nodetrust.tk	=>	×
2018-07-05T14:09:42.180Z libp2p:floodsub new peer QmTiZztTh33nuMFq5ZyW8mCrnzDbPP9zvaGV5UPXrcKR1B
2018-07-05T14:09:42.182Z libp2p:floodsub connected QmTiZztTh33nuMFq5ZyW8mCrnzDbPP9zvaGV5UPXrcKR1B
2018-07-05T14:09:42.183Z libp2p:floodsub rpc from QmTiZztTh33nuMFq5ZyW8mCrnzDbPP9zvaGV5UPXrcKR1B
2018-07-05T14:09:42.186Z libp2p:circuit:dialer HOP supported adding as relay - QmTiZztTh33nuMFq5ZyW8mCrnzDbPP9zvaGV5UPXrcKR1B
2018-07-05T14:09:42.272Z nodetrust:dns [208.69.32.73:39966#14329]	id0elg2wqm91z50kp2a8ratswm-bk1i9guixoqkpp.ip.libp2p-nodetrust.tk	=>	×
2018-07-05T14:09:42.363Z acme-v2 undefined
2018-07-05T14:09:42.364Z acme-v2 { statusCode: 400,
  body: 
   { type: 'urn:ietf:params:acme:error:malformed',
     detail: 'Error creating new order :: Invalid character in DNS name',
     status: 400 },
  headers: 
   { server: 'nginx',
     'content-type': 'application/problem+json',
     'content-length': '142',
     'boulder-requester': '35968123',
     'replay-nonce': 'kFSgAAUG9UwxVllhM58GlVnYLIP0xtV6r6R_I9lCmpY',
     expires: 'Thu, 05 Jul 2018 14:09:42 GMT',
     'cache-control': 'max-age=0, no-cache, no-store',
     pragma: 'no-cache',
     date: 'Thu, 05 Jul 2018 14:09:42 GMT',
     connection: 'close' },
  request: 
   { uri: 
      Url {
        protocol: 'https:',
        slashes: true,
        auth: null,
        host: 'acme-v02.api.letsencrypt.org',
        port: 443,
        hostname: 'acme-v02.api.letsencrypt.org',
        hash: null,
        search: null,
        query: null,
        pathname: '/acme/new-order',
        path: '/acme/new-order',
        href: 'https://acme-v02.api.letsencrypt.org/acme/new-order' },
     method: 'POST',
     headers: 
      { 'User-Agent': 'Greenlock/1.0.9 (Linux; x64 linux 4.4.0-97-generic) Node.js/v8.11.3',
        'Content-Type': 'application/jose+json',
        accept: 'application/json',
        'content-length': 874 } } }
authorizations were not fetched:
{ type: 'urn:ietf:params:acme:error:malformed',
  detail: 'Error creating new order :: Invalid character in DNS name',
  status: 400 }
2018-07-05T14:09:42.365Z nodetrust:letsencrypt:acme:queue finished task @QmTiZztTh33nuMFq5ZyW8mCrnzDbPP9zvaGV5UPXrcKR1B,id0elhowuyg5nr5yrodcm58r9dn7p5qrujz-lspg-.ip.libp2p-nodetrust.tk!ip488-99-218-136.ip.libp2p-nodetrust.tk@id0elhowuyg5nr5yrodcm58r9dn7p5qrujz-lspg-.ip.libp2p-nodetrust.tk!ip488-99-218-136.ip.libp2p-nodetrust.tk
2018-07-05T14:09:42.365Z nodetrust:letsencrypt:acme:queue unlock domain id0elhowuyg5nr5yrodcm58r9dn7p5qrujz-lspg-.ip.libp2p-nodetrust.tk
2018-07-05T14:09:42.365Z nodetrust:letsencrypt:acme:queue unlock domain ip488-99-218-136.ip.libp2p-nodetrust.tk
2018-07-05T14:09:42.365Z nodetrust:protocol Error: authorizations were not fetched
    at /home/maciej/libp2p-nodetrust/server/node_modules/acme-v2/node.js:573:31
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
2018-07-05T14:09:42.368Z nodetrust:dns [208.69.32.73:42068#59819]	id0elg2wqm91z50kp2a8ratswm-bk1i9guixoqkpp.ip.libp2p-nodetrust.tk	=>	×
```

**Comment by mkg20001** [comment]
Resolved by removing `-` from domain base
